fix : 주문 페이징 오류 수정 및 리뷰관련 코드 수정
HONGVELOPER/NHN-project pull request #157
Opened 2022-08-22 17:34 UTC by kkb-98

관리자 주문목록 페이징과 유저 주문목록 페이징 오류 수정.
adminOnlyOrderView 대소문자 수정.
주문 취소 시 나의 주문목록에서 리뷰작성 버튼 숨김처리 및 상품 상세에 출력 되던 내가 쓴 리뷰 숨김 처리.

+ pr에 올라온 가격으로 검색 시 예외처리 코드는 머지가 되면 바로 반영하겠습니다!

2022-08-22 18:16 UTC, HONGVELOPER approved these changes
코드 확인했습니다. 고생하셨어요!

2022-08-22 18:16 UTC, HONGVELOPER commented on src/main/kotlin/nhncommerce/project/order/OrderService.kt
> +        }
리뷰 작성하지 못하도록 하는거 좋습니다!

2022-08-23 01:32 UTC, jsb12302 requested changes
OrderService에 price 검색할 때 문자열 들어오는것 도 에러 처리 해야할것 같아요~

2022-08-23 06:59 UTC, yoo2wo commented on src/main/kotlin/nhncommerce/project/order/OrderController.kt
>      fun orderListTest(pageRequestDTO: PageRequestDTO, model: Model): String {
orderListTest 지워야할거같아요!

2022-08-23 07:12 UTC, jsb12302 approved these changes

2022-08-23 07:17 UTC, merged